services:
  postgresql:
    container_name: practica_postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: practica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata